%this function estimates the background in photon counts inside an ROI 
%by calculating the averate of the pixels directly bordering an ROI.
function out = processROI(fullROI,fulloi,fullvari,fullgi,Kfull)
out = struct('ROI',fullROI(2:Kfull-1,2:Kfull-1),...
    'BACKGROUND',abs(...
    (...
    (1/(4*size(fullROI,2)-2))*(...
    sum(fullROI(1,1:Kfull))+...
    sum(fullROI(Kfull,1:Kfull))+...
    sum(full_ROI(2:Kfull-1,1))+...
    sum(fullROI(2:Kfull-1,Kfull)))...
    )*ones(size(ROI))...
    ),...
    'oi',abs(fulloi(2:end-1,2:end-1)),...
    'vari',abs(fullvari(2:end-1,2:end-1)),...
    'gi',bs(fullgi(2:end-1,2:end-1)));
end