classdef AnalyzeClass
    properties
        timestamp
        caltimestamp
        anlztimestamp
        Filedir
        PhasePlateType
        GLMPPFileName
        LookupTableFileName
        PupilPlaneFileName
        DATASpectralStructureFileName
        PSFDATASpectralStructureFileName
        outdir
        oiFileName
        variFileName
        giFileName
        EXPdir
        DATAdir
        CALdir
        PSFDATAdir
        FileIndexFileName
        FileIndex
        maindirectory
        filelisting
        startingframe
        numberframes
        framenumber
        LookupTableStructure
        oi
        vari
        gi
        DATASpectralStructure
        PSFDATASpectralStructure
        frame
        iternum
        plotyesno
        ftv1cell
        
        delta_lambda
        names
        SpecMax
        gauwidth
        gausigma
        SRX_vutaraHeaderInfo
        SRX_particles
        
        SRX_image_ID
        SRX_time_point
        SRX_cycle
        SRX_z_step
        SRX_frame
        SRX_accum
        SRX_probe
        SRX_photon_count
        SRX_photon_count11
        SRX_photon_count12
        SRX_photon_count21
        SRX_photon_count22
        SRX_psfx
        SRX_psfy
        SRX_psfz
        SRX_psf_photon_count
        SRX_x
        SRX_y
        SRX_z
        SRX_stdev
        SRX_amp
        SRX_background11
        SRX_background12
        SRX_background21
        SRX_background22
        SRX_maxResidueSlope
        SRX_chisq
        SRX_log_likelihood
        SRX_llr
        SRX_accuracy
        SRX_fiducial
        SRX_valid
        SRX_precisionx
        SRX_precisiony
        SRX_precisionz
        SRX_cluster_ID
        SRX_particle_ID
        SRX_custom_confidence1
        SRX_custom_confidence2
        SRX_custom_confidence3
    end
    methods
        function out = initcalibrate(Analyze,EXPdirin,...
            PSFDATAdirin,DATASpectralStructureFileNamein,...
            PSFDATASpectralStructureFileNamein,PhasePlateTypein)
            Analyze.timestamp=...
                string(datetime('now','TimeZone','UTC','Format','yyyyMMddHHmmss'));
            Analyze.EXPdir=EXPdirin;
            Analyze.CALdir=strcat(Analyze.EXPdir,'/CAL_',Analyze.timestamp);
            
            Analyze.PhasePlateType=PhasePlateTypein;                               
            Analyze.GLMPPFileName=...
                strcat(Analyze.EXPdir,'/GLMPP','_',Analyze.PhasePlateType,'_',Analyze.timestamp,'.csv');
            Analyze.LookupTableFileName=...
                strcat(Analyze.EXPdir,'/LookupTable','_',Analyze.PhasePlateType,'_',Analyze.timestamp,'.mat');
            Analyze.PupilPlaneFileName=...
                strcat(Analyze.EXPdir,'/PupilPlane','_',Analyze.PhasePlateType,'_',Analyze.timestamp,'.csv');
            Analyze.DATASpectralStructureFileName=...
                strcat(Analyze.EXPdir,DATASpectralStructureFileNamein,'.mat');
            Analyze.PSFDATASpectralStructureFileName=...
                strcat(Analyze.EXPdir,PSFDATASpectralStructureFileNamein,'.mat');
            Analyze.oiFileName=...
                strcat(Analyze.EXPdir,'/PIXSTAT/offset_map.tiff');
            Analyze.variFileName=...
                strcat(Analyze.EXPdir,'/PIXSTAT/variance_map.tiff');
            Analyze.giFileName=...
                strcat(Analyze.EXPdir,'/PIXSTAT/gain_map.tiff');
            Analyze.PSFDATAdir=...
                strcat(Analyze.EXPdir,PSFDATAdirin);
            
            Analyze.PSFDATASpectralStructure=load(...
                Analyze.PSFDATASpectralStructureFileName);
            
            Analyze.DATASpectralStructure=load(...
                Analyze.DATASpectralStructureFileName);
            
            out = Analyze;
        end
        function out = calibrate(Analyze,beadtagsin,FluorTagsin,excitlambdain,...
                            numberposin,framesatposin)
                        
            GLMPP=GLMPPClass;
            GLMPP=GLMPP.init('GLMPP_temp.csv');
            
            PupilPlane=PupilPlaneClass;
            PupilPlane=PupilPlane.init('PupilPlane_temp.csv');
            
            GibsonLaniPSF=GibsonLaniPSFClass;
            GibsonLaniPSF=GibsonLaniPSF.init(GLMPP,PupilPlane);
            
            %initialize the class that handles the PSF calibration as CalibratePSF
            CalibratePSF=CalibratePSFClass;
            CalibratePSF=CalibratePSF.init(GLMPP,...
                PupilPlane,...
                Analyze.PSFDATASpectralStructure,...
                beadtagsin,...
                excitlambdain,...
                numberposin,...
                framesatposin);

            %import PSF calibration data.
            CalibratePSF=CalibratePSF.importdata(Analyze.PSFDATAdir,...
                strcat(Analyze.EXPdir,'/PIXSTAT'));

            %select ROIs.
            CalibratePSF=CalibratePSF.selectROI(GLMPP);

            %fit the model to the calibration data.
            CalibratePSF=CalibratePSF.fminsearchllsCOMS(...
                GibsonLaniPSF,GLMPP,PupilPlane);

            %transfer the pupil plane values from the fit, from CalibratePSF to
            %PupilPlane.
            PupilPlane.THETAplate(:)=reshape(CalibratePSF.THETAplate(1,1,1:end),...
                1,numel(CalibratePSF.THETAplate(1,1,1:end)));
            PupilPlane.THETAZernike(:)=reshape(CalibratePSF.THETAZernike(1,1,1:end),...
                1,numel(CalibratePSF.THETAZernike(1,1,1:end)));

            %write the propery values of GLMPP and PupilPlane to a calibration file.
            GLMPP.write(Analyze.GLMPPFileName);
            PupilPlane.write(Analyze.PupilPlaneFileName);
            
            %GibsonLaniPSF must be redefined after the calibration is
            %complete so the PupilPlane has the correct pupil plane
            %information to make the lookuptable
            clear('GibsonLaniPSF');
            GibsonLaniPSF=GibsonLaniPSFClass;
            GibsonLaniPSF=GibsonLaniPSF.init(GLMPP,PupilPlane);
            
            GibsonLaniPSF=GibsonLaniPSF.bead(0,0,0,0.680);
            figure(5),imagesc(GibsonLaniPSF.PSF),axis image,colormap(gray);
            
            %create a lookup table with the fluorspectra
            LookupTable=LookupTableClass;
            LookupTable=LookupTable.init(Analyze.DATASpectralStructureFileName,...
                FluorTagsin,GLMPP);
            LookupTable=LookupTable.create(GibsonLaniPSF);
            LookupTable.write(Analyze.LookupTableFileName);
            
            mkdir(Analyze.CALdir);
            movefile(Analyze.GLMPPFileName,Analyze.CALdir);
            movefile(Analyze.PupilPlaneFileName,Analyze.CALdir);
            movefile(Analyze.LookupTableFileName,Analyze.CALdir);
            
            out = Analyze;
        end
        function out = initanalysis(Analyze,EXPdirin,caltimestampin,...
                DATASpectralStructureFileNamein,DATAdirin)

            Analyze.EXPdir=EXPdirin;
            ts=datetime('now','TimeZone','UTC','Format','yyyyMMddHHmmss');
            Analyze.anlztimestamp=string(ts);
            Analyze.outdir=strcat(...
                Analyze.EXPdir,'/','OUT','_',Analyze.anlztimestamp); 
            mkdir(Analyze.outdir);
            
            Analyze.caltimestamp=caltimestampin;
            Analyze.CALdir=strcat(Analyze.EXPdir,'/CAL_',Analyze.caltimestamp);
            listing=dir(Analyze.CALdir);
            for ii=1:numel(listing)
                filename = listing(ii).name;
                switch filename(1)
                    case 'G'
                        Analyze.GLMPPFileName=strcat(Analyze.CALdir,...
                            '/',listing(ii).name);
                    case 'P'
                        Analyze.PupilPlaneFileName=strcat(Analyze.CALdir,...
                            '/',listing(ii).name);
                    case 'L'
                        Analyze.LookupTableFileName=strcat(Analyze.CALdir,...
                            '/',listing(ii).name);
                end
            end
                        
            Analyze.DATASpectralStructureFileName=...
                strcat(Analyze.EXPdir,DATASpectralStructureFileNamein);
            Analyze.DATAdir=strcat(Analyze.EXPdir,DATAdirin);
            Analyze.oiFileName=...
                strcat(Analyze.EXPdir,'/PIXSTAT/offset_map.tiff');
            Analyze.variFileName=...
                strcat(Analyze.EXPdir,'/PIXSTAT/variance_map.tiff');
            Analyze.giFileName=...
                strcat(Analyze.EXPdir,'/PIXSTAT/gain_map.tiff');      
            
            Analyze.FileIndex={'CAL',Analyze.CALdir;... %CALdir contains, GLMPP_timestamp, PupilPlane_timestamp, LookupTable_timestamp, and PSFDATAdir
                'DATASpectralStructure',Analyze.DATASpectralStructureFileName;...
                'PSFDATASpectralStructure',Analyze.PSFDATASpectralStructureFileName;...
                'oi',Analyze.oiFileName;...
                'vari',Analyze.variFileName;...
                'gi',Analyze.giFileName;...
                'DATA',Analyze.DATAdir};
                        
            Analyze.FileIndexFileName=strcat(Analyze.outdir,'/FileIndex.csv');
            writecell(Analyze.FileIndex,Analyze.FileIndexFileName,'Delimiter','comma');

            fileID=fopen(Analyze.FileIndexFileName);
            Analyze.FileIndex=textscan(fileID, '%s %s', 'delimiter',',');
            fclose(fileID);
            
            for ii=1:size(Analyze.FileIndex{1},1)
                filestring=Analyze.FileIndex{1}{ii};
                switch filestring
                    case 'GLMPP'
                        Analyze.GLMPPFileName=Analyze.FileIndex{2}{ii};
                    case 'LookupTable'
                        Analyze.LookupTableFileName=Analyze.FileIndex{2}{ii};
                    case 'PupilPlane'
                        Analyze.PupilPlaneFileName=Analyze.FileIndex{2}{ii};
                    case 'DATASpectralStructure'
                        Analyze.DATASpectralStructureFileName=Analyze.FileIndex{2}{ii};
                    case 'PSFDATASpectralStructure'
                        Analyze.PSFDATASpectralStructureFileName=Analyze.FileIndex{2}{ii};
                    case 'oi'
                        Analyze.oiFileName=Analyze.FileIndex{2}{ii};
                    case 'vari'
                        Analyze.variFileName=Analyze.FileIndex{2}{ii};
                    case 'gi'
                        Analyze.giFileName=Analyze.FileIndex{2}{ii};
                    case 'DATA'
                        Analyze.DATAdir=Analyze.FileIndex{2}{ii};
                end
            end
            
            Analyze.SRX_vutaraHeaderInfo = {'image-ID','time-point','cycle',...
                'z-step','frame','accum','probe','photon-count',...
                'photon-count11','photon-count12','photon-count21',...
                'photon-count22','psfx','psfy','psfz',...
                'psf-photon-count','x','y','z','amp',...
                'background11','background12','background21',...
                'background22','maxResidualSlope','chisq',...
                'log-likelihood','llr','accuracy','fiducial','valid',...
                'precisionx','precisiony','precisionz','cluster-ID',...
                'particle-ID','custom-confidence1','custom-confidence2',...
                'custom-confidence3'};
            Analyze.SRX_particles=[];
            
            Analyze.DATASpectralStructure=load(Analyze.DATASpectralStructureFileName);
            Analyze.names=fieldnames(Analyze.DATASpectralStructure);
            Analyze.SpecMax=single(zeros(1,2));
            for ii=1:numel(Analyze.SpecMax)
                Analyze.SpecMax(ii)=...
                    Analyze.DATASpectralStructure.(Analyze.names{ii}).Wavelength(...
                        (...
                            max(...
                            Analyze.DATASpectralStructure.(Analyze.names{ii}).Spectrum.*...
                            Analyze.DATASpectralStructure.(Analyze.names{ii}).Filter)==...
                            (Analyze.DATASpectralStructure.(Analyze.names{ii}).Spectrum.*...
                            Analyze.DATASpectralStructure.(Analyze.names{ii}).Filter)...
                        )...
                    );
            end
                           
            Analyze.LookupTableStructure=load(Analyze.LookupTableFileName);
            Analyze.oi=cast(imread(Analyze.oiFileName),'single');
            Analyze.vari=cast(imread(Analyze.variFileName),'single');
            Analyze.gi=cast(imread(Analyze.giFileName),'single');
            Analyze.frame=single(1);
            Analyze.iternum=single(100);
            Analyze.startingframe=single(1);
            Analyze.numberframes=single(1);
            Analyze.DATASpectralStructure=load(...
                Analyze.DATASpectralStructureFileName);
            Analyze.maindirectory=pwd;
            cd(Analyze.DATAdir);
            Analyze.filelisting=dir('*.tif');
            cd(Analyze.maindirectory);
            
            out = Analyze;
        end
        function out = plotlocalizations(Analyze,SegmentData,...
                GibsonLaniPSF,GLMPP)
            figure('Name','FIT/ROI comparison')
            for rr = 1:numel(SegmentData.ROIstruct)
                
                GibsonLaniPSF=GibsonLaniPSF.bead(...
                    SegmentData.ROIstruct(rr).ftvl1(1),...
                    SegmentData.ROIstruct(rr).ftvl1(2),...
                    SegmentData.ROIstruct(rr).ftvl1(3),...
                    SegmentData.ROIstruct(rr).ftvl1(4));
                MODEL=(SegmentData.ROIstruct(rr).Nphoton*...
                    GibsonLaniPSF.PSF+...
                    SegmentData.ROIstruct(rr).BACKGROUND).*...
                    SegmentData.ROIstruct(rr).gi+...
                    SegmentData.ROIstruct(rr).oi;
                Chi2=sum(sum(...
                    ((SegmentData.ROIstruct(rr).ROI-MODEL).^2)./...
                    MODEL...
                    ));
                df=GLMPP.K.^2-1;
                P_val=1-chi2cdf(Chi2,df);
                subplot(round(numel(SegmentData.ROIstruct)/4)+1,4,rr)
                temp=cat(2,MODEL,SegmentData.ROIstruct(rr).ROI);
                imagesc(temp), axis image, colormap(gray);
                colorbar
                title(sprintf('Chi2=%0.3g,P-value=%0.3g',Chi2,P_val));
            end
            out = Analyze;
        end
        function out = plotlocalizationsvarblur(Analyze,SegmentData,...
                GibsonLaniPSF,GLMPP)
            figure('Name','FIT/ROI comparison')
            for rr = 1:numel(SegmentData.ROIstruct)
                
                display(SegmentData.ROIstruct(rr).ftvl(:))
                display(mean2(SegmentData.ROIstruct(rr).Background))
                
                GibsonLaniPSF=GibsonLaniPSF.varblur(...
                    SegmentData.ROIstruct(rr).ftvl1(1),...
                    SegmentData.ROIstruct(rr).ftvl1(2),...
                    SegmentData.ROIstruct(rr).ftvl1(3),...
                    SegmentData.ROIstruct(rr).ftvl1(4));
                MODEL=(SegmentData.ROIstruct(rr).Nphoton*...
                    GibsonLaniPSF.PSF+...
                    SegmentData.ROIstruct(rr).BACKGROUND).*...
                    SegmentData.ROIstruct(rr).gi+...
                    SegmentData.ROIstruct(rr).oi;
                Chi2=sum(sum(...
                    ((SegmentData.ROIstruct(rr).ROI-MODEL).^2)./...
                    MODEL...
                    ));
                df=GLMPP.K.^2-1;
                P_val=chi2cdf(Chi2,df);
                subplot(round(numel(SegmentData.ROIstruct)/4)+1,4,rr)
                temp=cat(2,MODEL,SegmentData.ROIstruct(rr).ROI);
                imagesc(temp), axis image, colormap(gray);
                colorbar
                title(sprintf('Chi2=%0.3g,P-value=%0.3g',Chi2,P_val));
            end
            out = Analyze;
        end
        function out = frames(Analyze,startingframein,numberframesin,...
                iternumin,plotyesnoin)
            Analyze.startingframe=single(startingframein);
            Analyze.numberframes=single(numberframesin);
            Analyze.iternum=single(iternumin);
            Analyze.plotyesno=plotyesnoin;
            
            h=waitbar(0,'1','Name','Analyzing frames...',...
                'CreateCancelBtn','setappdata(gcbf,''canceling'',1)');
            
            setappdata(h,'canceling',0);
            
            countframe = 0;
            endframe=Analyze.startingframe+Analyze.numberframes;
            if (endframe>numel(Analyze.filelisting))
                endframe=numel(Analyze.filelisting);
            end
            for ff = Analyze.startingframe:endframe
                
                if getappdata(h,'canceling')
                    break
                end
                
                Analyze.frame=cast(imread(fullfile(...
                Analyze.DATAdir,Analyze.filelisting(ff).name)),...
                'single');

                GLMPP=GLMPPClass;
                GLMPP=GLMPP.init('GLMPP_temp.csv');
                %GLMPP=GLMPP.update(Analyze.GLMPPFileName);
                
                PupilPlane=PupilPlaneClass;
                PupilPlane=PupilPlane.init('PupilPlane_temp.csv');
                PupilPlane=PupilPlane.update(Analyze.PupilPlaneFileName);
                
                GibsonLaniPSF=GibsonLaniPSFClass;
                GibsonLaniPSF=GibsonLaniPSF.init(GLMPP,PupilPlane);
                
                SegmentData=SegmentDataClass;
                SegmentData=SegmentData.init(GLMPP,Analyze.frame,...
                    Analyze.oi,Analyze.vari,Analyze.gi);
                SegmentData=SegmentData.selectROIs(GLMPP);
                ROIstruct=SegmentData.ROIstruct;
                
                if (~isempty(ROIstruct(1).ROI))
                    countframe = countframe+1;
                    LT=Analyze.LookupTableStructure;
                    IN=Analyze.iternum;

                    %filter out empty elements of ROIstruct            
                    parfor rr=1:numel(ROIstruct)
                
                        Localize=LocalizeClass;
                        Localize=Localize.init(...
                            ROIstruct(rr).ROI,...
                            ROIstruct(rr).BACKGROUND,...
                            ROIstruct(rr).vari,...
                            ROIstruct(rr).oi,...
                            ROIstruct(rr).gi,...
                            LT,...
                            IN);
                        Localize=Localize.guess(GLMPP);
                        ROIstruct(rr).ftvl0=Localize.ftvl0;
                        Localize=Localize.data(GibsonLaniPSF);
                        ROIstruct(rr).ftvl1=Localize.ftvl1;       
                    end
    
                    SegmentData.ROIstruct=ROIstruct;
                    
                    if (strcmp(Analyze.plotyesno,'yes')==1)
                        Analyze=...
                            Analyze.plotlocalizations(SegmentData,GibsonLaniPSF,...
                            GLMPP);
                    end

                    for rr=1:numel(ROIstruct)

                        GibsonLaniPSF=GibsonLaniPSF.intens(...
                            ROIstruct(rr).ftvl1(1),...
                            ROIstruct(rr).ftvl1(2),...
                            ROIstruct(rr).ftvl1(3),...
                            ROIstruct(rr).ftvl1(4));
                        mu=(ROIstruct(rr).Nphoton*GibsonLaniPSF.PSF+...
                            ROIstruct(rr).BACKGROUND);
                        GibsonLaniPSF=GibsonLaniPSF.ddx0(...
                            ROIstruct(rr).ftvl1(1),...
                            ROIstruct(rr).ftvl1(2),...
                            ROIstruct(rr).ftvl1(3),...
                            ROIstruct(rr).ftvl1(4));
                        ddx0mu=(ROIstruct(rr).Nphoton*GibsonLaniPSF.ddx0PSF);
                        GibsonLaniPSF=GibsonLaniPSF.ddy0(...
                            ROIstruct(rr).ftvl1(1),...
                            ROIstruct(rr).ftvl1(2),...
                            ROIstruct(rr).ftvl1(3),...
                            ROIstruct(rr).ftvl1(4));
                        ddy0mu=(ROIstruct(rr).Nphoton*GibsonLaniPSF.ddy0PSF);
                        GibsonLaniPSF=GibsonLaniPSF.ddzp(...
                            ROIstruct(rr).ftvl1(1),...
                            ROIstruct(rr).ftvl1(2),...
                            ROIstruct(rr).ftvl1(3),...
                            ROIstruct(rr).ftvl1(4));
                        ddzpmu=(ROIstruct(rr).Nphoton*GibsonLaniPSF.ddzpPSF);
                        %GibsonLaniPSF=GibsonLaniPSF.ddlambda(...
                        %    ROIstruct(rr).ftvl1(1),...
                        %    ROIstruct(rr).ftvl1(2),...
                        %    ROIstruct(rr).ftvl1(3),...
                        %    ROIstruct(rr).ftvl1(4));
                        %ddlambdamu=(ROIstruct(rr).Nphoton*GibsonLaniPSF.ddlambdaPSF);
                        GibsonLaniPSF=GibsonLaniPSF.loglikelihood(...
                            ROIstruct(rr).ROI,...
                            ROIstruct(rr).BACKGROUND,...
                            ROIstruct(rr).ftvl1(1),...
                            ROIstruct(rr).ftvl1(2),...
                            ROIstruct(rr).ftvl1(3),...
                            ROIstruct(rr).ftvl1(4));
                        GibsonLaniPSF=GibsonLaniPSF.loglikelihoodratio(...
                            ROIstruct(rr).ROI,...
                            ROIstruct(rr).BACKGROUND,...
                            ROIstruct(rr).vari,...
                            ROIstruct(rr).gi,...
                            ROIstruct(rr).oi,...
                            ROIstruct(rr).ftvl1(1),...
                            ROIstruct(rr).ftvl1(2),...
                            ROIstruct(rr).ftvl1(3),...
                            ROIstruct(rr).ftvl1(4));

                        Analyze.delta_lambda=abs(ROIstruct(rr).ftvl1(4)-Analyze.SpecMax);

                        Analyze.SRX_image_ID=ff;
                        Analyze.SRX_time_point=0;
                        Analyze.SRX_cycle=0;
                        Analyze.SRX_z_step=0;
                        Analyze.SRX_frame=ff;
                        Analyze.SRX_accum=0;
                        Analyze.SRX_probe=...
                            find(Analyze.delta_lambda==min(Analyze.delta_lambda))-1;
                        Analyze.SRX_photon_count=ROIstruct(rr).Nphoton+sum(sum(ROIstruct(rr).BACKGROUND));
                        Analyze.SRX_photon_count11=(ROIstruct(rr).Nphoton+sum(sum(ROIstruct(rr).BACKGROUND)))/4;
                        Analyze.SRX_photon_count12=(ROIstruct(rr).Nphoton+sum(sum(ROIstruct(rr).BACKGROUND)))/4;
                        Analyze.SRX_photon_count21=(ROIstruct(rr).Nphoton+sum(sum(ROIstruct(rr).BACKGROUND)))/4;
                        Analyze.SRX_photon_count22=(ROIstruct(rr).Nphoton+sum(sum(ROIstruct(rr).BACKGROUND)))/4;
                        Analyze.SRX_psfx=1000*abs(ROIstruct(rr).ftvl1(1)-ROIstruct(rr).ftvl0(1));
                        Analyze.SRX_psfy=1000*abs(ROIstruct(rr).ftvl1(2)-ROIstruct(rr).ftvl0(2));
                        Analyze.SRX_psfz=1000*abs(ROIstruct(rr).ftvl1(3)-ROIstruct(rr).ftvl0(3));
                        Analyze.SRX_psf_photon_count=ROIstruct(rr).Nphoton;
                        Analyze.SRX_x=1000*((GLMPP.PixelSize/GLMPP.M)*(ROIstruct(rr).ROIposition(1)+(GLMPP.K/2-1+1/2))+ROIstruct(rr).ftvl1(1));
                        Analyze.SRX_y=1000*((GLMPP.PixelSize/GLMPP.M)*(ROIstruct(rr).ROIposition(2)+(GLMPP.K/2-1+1/2))+ROIstruct(rr).ftvl1(2));
                        Analyze.SRX_z=1000*ROIstruct(rr).ftvl1(3);
                        Analyze.SRX_amp=max(max(...
                                ROIstruct(rr).Nphoton*...
                                mean2(ROIstruct(rr).gi)*...
                                GibsonLaniPSF.PSF...
                            ));
                        Analyze.SRX_background11=mean2(ROIstruct(rr).BACKGROUND.*ROIstruct(rr).gi+ROIstruct(rr).oi);
                        Analyze.SRX_background12=mean2(ROIstruct(rr).BACKGROUND.*ROIstruct(rr).gi+ROIstruct(rr).oi);
                        Analyze.SRX_background21=mean2(ROIstruct(rr).BACKGROUND.*ROIstruct(rr).gi+ROIstruct(rr).oi);
                        Analyze.SRX_background22=mean2(ROIstruct(rr).BACKGROUND.*ROIstruct(rr).gi+ROIstruct(rr).oi);
                        Analyze.SRX_maxResidueSlope=(max(max(ROIstruct(rr).ROI))-...
                            min(min(ROIstruct(rr).ROI)))/size(ROIstruct(rr).ROI,1);
                        Analyze.SRX_chisq=sum(sum(...
                            ((mu-((ROIstruct(rr).ROI-ROIstruct(rr).oi)./ROIstruct(rr).gi)).^2)./mu...
                            ));
                        Analyze.SRX_log_likelihood=GibsonLaniPSF.logL;
                        Analyze.SRX_accuracy=(1000*ROIstruct(rr).ftvl1(4)/(2*GLMPP.NA)); %rough value for width of the PSF from the Webb paper in nm
                        Analyze.SRX_llr=GibsonLaniPSF.llr;
                        Analyze.SRX_fiducial=0;
                        Analyze.SRX_valid=1;

                        Ifish=[sum(sum(ddx0mu.*ddx0mu./mu)), sum(sum(ddx0mu.*ddy0mu./mu)), sum(sum(ddx0mu.*ddzpmu./mu));...
                               sum(sum(ddy0mu.*ddx0mu./mu)), sum(sum(ddy0mu.*ddy0mu./mu)), sum(sum(ddy0mu.*ddzpmu./mu));...
                               sum(sum(ddzpmu.*ddx0mu./mu)), sum(sum(ddzpmu.*ddy0mu./mu)), sum(sum(ddzpmu.*ddzpmu./mu))];
                        invIfish=inv(Ifish);                
                        Analyze.SRX_precisionx=sqrt(1000*invIfish(1,1));
                        Analyze.SRX_precisiony=sqrt(1000*invIfish(2,2));
                        Analyze.SRX_precisionz=sqrt(1000*invIfish(3,3)*GLMPP.M^2);
                        Analyze.SRX_cluster_ID=0;
                        Analyze.SRX_particle_ID=-1;
                        Analyze.SRX_custom_confidence1=0;
                        Analyze.SRX_custom_confidence2=0;
                        Analyze.SRX_custom_confidence3=0;

                        if ((abs(Analyze.SRX_psfx)<20000) && (abs(Analyze.SRX_psfy)<20000) && (abs(Analyze.SRX_psfz)<2000) && (abs(Analyze.SRX_precisionx)<500) && (abs(Analyze.SRX_precisiony)<500) && (abs(Analyze.SRX_precisionz)<500))

                            Analyze.SRX_particles=cat(1,Analyze.SRX_particles,...
                                [Analyze.SRX_image_ID,...
                                Analyze.SRX_time_point,...
                                Analyze.SRX_cycle,...
                                Analyze.SRX_z_step,...
                                Analyze.SRX_frame,...
                                Analyze.SRX_accum,...
                                Analyze.SRX_probe,...
                                Analyze.SRX_photon_count,...
                                Analyze.SRX_photon_count11,...
                                Analyze.SRX_photon_count12,...
                                Analyze.SRX_photon_count21,...
                                Analyze.SRX_photon_count22,...
                                Analyze.SRX_psfx,...
                                Analyze.SRX_psfy,...
                                Analyze.SRX_psfz,...
                                Analyze.SRX_psf_photon_count,...
                                Analyze.SRX_x,...
                                Analyze.SRX_y,...
                                Analyze.SRX_z,...
                                Analyze.SRX_amp,...
                                Analyze.SRX_background11,...
                                Analyze.SRX_background12,...
                                Analyze.SRX_background21,...
                                Analyze.SRX_background22,...
                                Analyze.SRX_maxResidueSlope,...
                                Analyze.SRX_chisq,...
                                Analyze.SRX_log_likelihood,...
                                Analyze.SRX_llr,...
                                Analyze.SRX_accuracy,...
                                Analyze.SRX_fiducial,...
                                Analyze.SRX_valid,...
                                Analyze.SRX_precisionx,...
                                Analyze.SRX_precisiony,...
                                Analyze.SRX_precisionz,...
                                Analyze.SRX_cluster_ID,...
                                Analyze.SRX_particle_ID,...
                                Analyze.SRX_custom_confidence1,...
                                Analyze.SRX_custom_confidence2,...
                                Analyze.SRX_custom_confidence3]);
           
                        end
                    end
                end
                waitbar((ff-Analyze.startingframe)/...
                    (Analyze.numberframes),h,sprintf(...
                    '%d/%d frames',(ff-Analyze.startingframe),...
                    (Analyze.numberframes)));
            end
            delete(h)
            out = Analyze;
        end
        function out = framesvarblurxyzlb(Analyze,startingframein,numberframesin,...
                iternumin,plotyesnoin)
            Analyze.startingframe=single(startingframein);
            Analyze.numberframes=single(numberframesin);
            Analyze.iternum=single(iternumin);
            Analyze.plotyesno=plotyesnoin;
            
            h=waitbar(0,'1','Name','Analyzing frames...',...
                'CreateCancelBtn','setappdata(gcbf,''canceling'',1)');
            
            setappdata(h,'canceling',0);
            
            countframe = 0;
            endframe=Analyze.startingframe+Analyze.numberframes;
            if (endframe>numel(Analyze.filelisting))
                endframe=numel(Analyze.filelisting);
            end
            for ff = Analyze.startingframe:endframe
                
                if getappdata(h,'canceling')
                    break
                end
                
                Analyze.frame=cast(imread(fullfile(...
                Analyze.DATAdir,Analyze.filelisting(ff).name)),...
                'single');

                GLMPP=GLMPPClass;
                GLMPP=GLMPP.init('GLMPP_temp.csv');
                %GLMPP=GLMPP.update(Analyze.GLMPPFileName);
                
                PupilPlane=PupilPlaneClass;
                PupilPlane=PupilPlane.init('PupilPlane_temp.csv');
                PupilPlane=PupilPlane.update(Analyze.PupilPlaneFileName);
                
                GibsonLaniPSF=GibsonLaniPSFClass;
                GibsonLaniPSF=GibsonLaniPSF.init(GLMPP,PupilPlane);
                
                SegmentData=SegmentDataClass;
                SegmentData=SegmentData.init(GLMPP,Analyze.frame,...
                    Analyze.oi,Analyze.vari,Analyze.gi);
                SegmentData=SegmentData.selectROIs(GLMPP);
                ROIstruct=SegmentData.ROIstruct;
                
                if (~isempty(ROIstruct(1).ROI))
                    countframe = countframe+1;
                    LT=Analyze.LookupTableStructure;
                    IN=Analyze.iternum;

                    %filter out empty elements of ROIstruct            
                    for rr=1:numel(ROIstruct)
                
                        Localize=LocalizeClass;
                        Localize=Localize.init(...
                            ROIstruct(rr).ROI,...
                            ROIstruct(rr).BACKGROUND,...
                            ROIstruct(rr).vari,...
                            ROIstruct(rr).oi,...
                            ROIstruct(rr).gi,...
                            LT,...
                            IN);
                        Localize=Localize.guess(GLMPP);
                        ROIstruct(rr).ftvl0=Localize.ftvl0;
                        Localize=Localize.datavarblurxyzlb(GibsonLaniPSF);
                        ROIstruct(rr).ftvl1=Localize.ftvl1(1:4);
                        ROIstruct(rr).BACKGROUND=Localize.FITBACKGROUND;
                        ROIstruct(rr).Nphoton=Localize.Nphoton;
                    end
    
                    SegmentData.ROIstruct=ROIstruct;
                    
                    if (strcmp(Analyze.plotyesno,'yes')==1)
                        Analyze=...
                            Analyze.plotlocalizations(SegmentData,GibsonLaniPSF,...
                            GLMPP);
                    end

                    for rr=1:numel(ROIstruct)

                        GibsonLaniPSF=GibsonLaniPSF.intens(...
                            ROIstruct(rr).ftvl1(1),...
                            ROIstruct(rr).ftvl1(2),...
                            ROIstruct(rr).ftvl1(3),...
                            ROIstruct(rr).ftvl1(4));
                        mu=(ROIstruct(rr).Nphoton*GibsonLaniPSF.PSF+...
                            ROIstruct(rr).BACKGROUND);
                        GibsonLaniPSF=GibsonLaniPSF.ddx0(...
                            ROIstruct(rr).ftvl1(1),...
                            ROIstruct(rr).ftvl1(2),...
                            ROIstruct(rr).ftvl1(3),...
                            ROIstruct(rr).ftvl1(4));
                        ddx0mu=(ROIstruct(rr).Nphoton*GibsonLaniPSF.ddx0PSF);
                        GibsonLaniPSF=GibsonLaniPSF.ddy0(...
                            ROIstruct(rr).ftvl1(1),...
                            ROIstruct(rr).ftvl1(2),...
                            ROIstruct(rr).ftvl1(3),...
                            ROIstruct(rr).ftvl1(4));
                        ddy0mu=(ROIstruct(rr).Nphoton*GibsonLaniPSF.ddy0PSF);
                        GibsonLaniPSF=GibsonLaniPSF.ddzp(...
                            ROIstruct(rr).ftvl1(1),...
                            ROIstruct(rr).ftvl1(2),...
                            ROIstruct(rr).ftvl1(3),...
                            ROIstruct(rr).ftvl1(4));
                        ddzpmu=(ROIstruct(rr).Nphoton*GibsonLaniPSF.ddzpPSF);
                        %GibsonLaniPSF=GibsonLaniPSF.ddlambda(...
                        %    ROIstruct(rr).ftvl1(1),...
                        %    ROIstruct(rr).ftvl1(2),...
                        %    ROIstruct(rr).ftvl1(3),...
                        %    ROIstruct(rr).ftvl1(4));
                        %ddlambdamu=(ROIstruct(rr).Nphoton*GibsonLaniPSF.ddlambdaPSF);
                        GibsonLaniPSF=GibsonLaniPSF.loglikelihood(...
                            ROIstruct(rr).ROI,...
                            ROIstruct(rr).BACKGROUND,...
                            ROIstruct(rr).ftvl1(1),...
                            ROIstruct(rr).ftvl1(2),...
                            ROIstruct(rr).ftvl1(3),...
                            ROIstruct(rr).ftvl1(4));
                        GibsonLaniPSF=GibsonLaniPSF.loglikelihoodratio(...
                            ROIstruct(rr).ROI,...
                            ROIstruct(rr).BACKGROUND,...
                            ROIstruct(rr).vari,...
                            ROIstruct(rr).gi,...
                            ROIstruct(rr).oi,...
                            ROIstruct(rr).ftvl1(1),...
                            ROIstruct(rr).ftvl1(2),...
                            ROIstruct(rr).ftvl1(3),...
                            ROIstruct(rr).ftvl1(4));

                        Analyze.delta_lambda=abs(ROIstruct(rr).ftvl1(4)-Analyze.SpecMax);

                        Analyze.SRX_image_ID=ff;
                        Analyze.SRX_time_point=0;
                        Analyze.SRX_cycle=0;
                        Analyze.SRX_z_step=0;
                        Analyze.SRX_frame=ff;
                        Analyze.SRX_accum=0;
                        Analyze.SRX_probe=...
                            find(Analyze.delta_lambda==min(Analyze.delta_lambda))-1;
                        Analyze.SRX_photon_count=ROIstruct(rr).Nphoton+sum(sum(ROIstruct(rr).BACKGROUND));
                        Analyze.SRX_photon_count11=(ROIstruct(rr).Nphoton+sum(sum(ROIstruct(rr).BACKGROUND)))/4;
                        Analyze.SRX_photon_count12=(ROIstruct(rr).Nphoton+sum(sum(ROIstruct(rr).BACKGROUND)))/4;
                        Analyze.SRX_photon_count21=(ROIstruct(rr).Nphoton+sum(sum(ROIstruct(rr).BACKGROUND)))/4;
                        Analyze.SRX_photon_count22=(ROIstruct(rr).Nphoton+sum(sum(ROIstruct(rr).BACKGROUND)))/4;
                        Analyze.SRX_psfx=1000*abs(ROIstruct(rr).ftvl1(1)-ROIstruct(rr).ftvl0(1));
                        Analyze.SRX_psfy=1000*abs(ROIstruct(rr).ftvl1(2)-ROIstruct(rr).ftvl0(2));
                        Analyze.SRX_psfz=1000*abs(ROIstruct(rr).ftvl1(3)-ROIstruct(rr).ftvl0(3));
                        Analyze.SRX_psf_photon_count=ROIstruct(rr).Nphoton;
                        Analyze.SRX_x=1000*((GLMPP.PixelSize/GLMPP.M)*(ROIstruct(rr).ROIposition(1)+(GLMPP.K/2-1+1/2))+ROIstruct(rr).ftvl1(1));
                        Analyze.SRX_y=1000*((GLMPP.PixelSize/GLMPP.M)*(ROIstruct(rr).ROIposition(2)+(GLMPP.K/2-1+1/2))+ROIstruct(rr).ftvl1(2));
                        Analyze.SRX_z=1000*ROIstruct(rr).ftvl1(3);
                        Analyze.SRX_amp=max(max(...
                                ROIstruct(rr).Nphoton*...
                                mean2(ROIstruct(rr).gi)*...
                                GibsonLaniPSF.PSF...
                            ));
                        Analyze.SRX_background11=mean2(ROIstruct(rr).BACKGROUND.*ROIstruct(rr).gi+ROIstruct(rr).oi);
                        Analyze.SRX_background12=mean2(ROIstruct(rr).BACKGROUND.*ROIstruct(rr).gi+ROIstruct(rr).oi);
                        Analyze.SRX_background21=mean2(ROIstruct(rr).BACKGROUND.*ROIstruct(rr).gi+ROIstruct(rr).oi);
                        Analyze.SRX_background22=mean2(ROIstruct(rr).BACKGROUND.*ROIstruct(rr).gi+ROIstruct(rr).oi);
                        Analyze.SRX_maxResidueSlope=(max(max(ROIstruct(rr).ROI))-...
                            min(min(ROIstruct(rr).ROI)))/size(ROIstruct(rr).ROI,1);
                        Analyze.SRX_chisq=sum(sum(...
                            ((mu-((ROIstruct(rr).ROI-ROIstruct(rr).oi)./ROIstruct(rr).gi)).^2)./mu...
                            ));
                        Analyze.SRX_log_likelihood=GibsonLaniPSF.logL;
                        Analyze.SRX_accuracy=(1000*ROIstruct(rr).ftvl1(4)/(2*GLMPP.NA)); %rough value for width of the PSF from the Webb paper in nm
                        Analyze.SRX_llr=GibsonLaniPSF.llr;
                        Analyze.SRX_fiducial=0;
                        Analyze.SRX_valid=1;

                        Ifish=[sum(sum(ddx0mu.*ddx0mu./mu)), sum(sum(ddx0mu.*ddy0mu./mu)), sum(sum(ddx0mu.*ddzpmu./mu));...
                               sum(sum(ddy0mu.*ddx0mu./mu)), sum(sum(ddy0mu.*ddy0mu./mu)), sum(sum(ddy0mu.*ddzpmu./mu));...
                               sum(sum(ddzpmu.*ddx0mu./mu)), sum(sum(ddzpmu.*ddy0mu./mu)), sum(sum(ddzpmu.*ddzpmu./mu))];
                        invIfish=inv(Ifish);                
                        Analyze.SRX_precisionx=sqrt(1000*invIfish(1,1));
                        Analyze.SRX_precisiony=sqrt(1000*invIfish(2,2));
                        Analyze.SRX_precisionz=sqrt(1000*invIfish(3,3)*GLMPP.M^2);
                        Analyze.SRX_cluster_ID=0;
                        Analyze.SRX_particle_ID=-1;
                        Analyze.SRX_custom_confidence1=0;
                        Analyze.SRX_custom_confidence2=0;
                        Analyze.SRX_custom_confidence3=0;

                        if ((abs(Analyze.SRX_psfx)<20000) && (abs(Analyze.SRX_psfy)<20000) && (abs(Analyze.SRX_psfz)<2000) && (abs(Analyze.SRX_precisionx)<500) && (abs(Analyze.SRX_precisiony)<500) && (abs(Analyze.SRX_precisionz)<500))

                            Analyze.SRX_particles=cat(1,Analyze.SRX_particles,...
                                [Analyze.SRX_image_ID,...
                                Analyze.SRX_time_point,...
                                Analyze.SRX_cycle,...
                                Analyze.SRX_z_step,...
                                Analyze.SRX_frame,...
                                Analyze.SRX_accum,...
                                Analyze.SRX_probe,...
                                Analyze.SRX_photon_count,...
                                Analyze.SRX_photon_count11,...
                                Analyze.SRX_photon_count12,...
                                Analyze.SRX_photon_count21,...
                                Analyze.SRX_photon_count22,...
                                Analyze.SRX_psfx,...
                                Analyze.SRX_psfy,...
                                Analyze.SRX_psfz,...
                                Analyze.SRX_psf_photon_count,...
                                Analyze.SRX_x,...
                                Analyze.SRX_y,...
                                Analyze.SRX_z,...
                                Analyze.SRX_amp,...
                                Analyze.SRX_background11,...
                                Analyze.SRX_background12,...
                                Analyze.SRX_background21,...
                                Analyze.SRX_background22,...
                                Analyze.SRX_maxResidueSlope,...
                                Analyze.SRX_chisq,...
                                Analyze.SRX_log_likelihood,...
                                Analyze.SRX_llr,...
                                Analyze.SRX_accuracy,...
                                Analyze.SRX_fiducial,...
                                Analyze.SRX_valid,...
                                Analyze.SRX_precisionx,...
                                Analyze.SRX_precisiony,...
                                Analyze.SRX_precisionz,...
                                Analyze.SRX_cluster_ID,...
                                Analyze.SRX_particle_ID,...
                                Analyze.SRX_custom_confidence1,...
                                Analyze.SRX_custom_confidence2,...
                                Analyze.SRX_custom_confidence3]);
           
                        end
                    end
                end
                waitbar((ff-Analyze.startingframe)/...
                    (Analyze.numberframes),h,sprintf(...
                    '%d/%d frames',(ff-Analyze.startingframe),...
                    (Analyze.numberframes)));
            end
            delete(h)
            out = Analyze;
        end
        function out = prepareparticlescsv(Analyze)
            vutaraCSVData=cast(Analyze.SRX_particles,'single');
            [~,nColVutaraCSV] = size(Analyze.SRX_vutaraHeaderInfo);

            % Create String for use with "fprintf" with the number of appropriate columns in "vutaraHeaderInfo"
            % Use "for" loop to iterate over size of "vutaraHeaderInfo" to generate string of proper size
            nColVutaraCell = cell(1,nColVutaraCSV-1);
            for i = 1:nColVutaraCSV-1
                nColVutaraCell{1,i} = '%s,';
            end
            % Append string to proper termination line call for "fprintf"
            nColVutaraCell = [nColVutaraCell{1,:},'%s\n'];

            % Choose desired file name and destination folder location for file saving
            %[saveFileName,saveDirectory,saveFilterIndex] = uiputfile('.csv','Save CSV File As...','particles.csv');
            %fullSavePathName = fullfile(saveDirectory,saveFileName);
            %if isequal(saveFileName,0) || isequal(saveDirectory,0) || isequal(saveFilterIndex,0)
            %    disp('User Cancelled File Save...')
            %else
            %    disp(['User saved file as:',fullSavePathName])
            %end

            % Save current working/home directory to use at end of function
            %homeDir = pwd;
            % Change to save directory
            %cd(saveDirectory);

            saveFileName='particles.csv';

            % Use "fprintf" to write the appropriate column headers to a CSV file called "particles.csv"
            fID = fopen(fullfile(Analyze.outdir,saveFileName),'w');
            fprintf(fID,nColVutaraCell,Analyze.SRX_vutaraHeaderInfo{1,:});
            fclose(fID);

            % Use "dlmwrite" to append ThunderStorm data to the CSV file with appropriate column headers
            % Variable "data" is the input data here, passed into the function call
            % Use 'roffset' value of '0' to avoid systemtatic output of ',' strings in first row from 'append' flag
            dlmwrite(fullfile(Analyze.outdir,saveFileName),vutaraCSVData,'delimiter',',','-append','roffset',0,'coffset',0);
            
            out = Analyze;
        end
        function out = preparedataxml(Analyze)
            dataxmlsource=strcat(Analyze.EXPdir,'/','data.xml');
            dataxmldestination=Analyze.outdir;
            copyfile(dataxmlsource,dataxmldestination);
            out = Analyze;
        end
    end
end
