classdef LookupTableClass
    properties
        deltax0
        deltay0
        deltazp
        x0range
        y0range
        zprange
        numx0pts
        numy0pts
        numzppts
        x0lnspace
        y0lnspace
        zplnspace
        
        fluortags
        names
        SS
        spectra
        filters
        wavelengths
        SpecMax
        nSpectrumPoints
        deltalambda
        
        codex
        xx0
        yy0
        zzp
        lll
        LT
        LookupTableStructure
    end
    methods
        function out = init(LookupTable,SpectralStructureFileName,...
                fluortagsin,GLMPP)
            LookupTable.deltax0=single(0.1); %in microns
            LookupTable.deltay0=single(0.1); %in microns
            LookupTable.deltazp=single(0.2); %in microns
            LookupTable.x0range=single([-0.25,0.25]);
            LookupTable.y0range=single([-0.25,0.25]);
            LookupTable.zprange=single([-1,1]);
            LookupTable.numx0pts=single(round(...
                (LookupTable.x0range(2)-...
                LookupTable.x0range(1))/LookupTable.deltax0...
                ));
            LookupTable.numy0pts=single(round(...
                (LookupTable.y0range(2)-...
                LookupTable.y0range(1))/LookupTable.deltay0...
                ));
            LookupTable.numzppts=single(round(...
                (LookupTable.zprange(2)-...
                LookupTable.zprange(1))/LookupTable.deltazp...
                ));
            
            LookupTable.x0lnspace=single(linspace(...
                -LookupTable.deltax0*(LookupTable.numx0pts-1)/2,...
                 LookupTable.deltax0*(LookupTable.numx0pts-1)/2,...
                 LookupTable.numx0pts));
            LookupTable.y0lnspace=single(linspace(...
                -LookupTable.deltay0*(LookupTable.numy0pts-1)/2,...
                 LookupTable.deltay0*(LookupTable.numy0pts-1)/2,...
                 LookupTable.numy0pts));
            LookupTable.zplnspace=single(linspace(...
                -LookupTable.deltazp*(LookupTable.numzppts-1)/2,...
                 LookupTable.deltazp*(LookupTable.numzppts-1)/2,...
                 LookupTable.numzppts));
            
            LookupTable.SS=load(SpectralStructureFileName);
            LookupTable.fluortags=fluortagsin;
            LookupTable.names=fieldnames(LookupTable.SS);
            
            LookupTable.spectra=single(zeros(numel(LookupTable.fluortags),...
                numel(LookupTable.SS.(LookupTable.names{1}).Spectrum)));
            
            LookupTable.filters=single(zeros(numel(LookupTable.fluortags),...
                numel(LookupTable.SS.(LookupTable.names{1}).Filter)));          
        
            LookupTable.wavelengths=single(zeros(numel(LookupTable.fluortags),...
                numel(LookupTable.SS.(LookupTable.names{1}).Wavelength)));    
            for ii=1:numel(LookupTable.fluortags)
                for jj=1:numel(LookupTable.names)
                    if strcmp(LookupTable.fluortags{ii},LookupTable.names{jj})
                        LookupTable.spectra(ii,:)=single(LookupTable.SS.(LookupTable.fluortags{ii}).Spectrum);
                        LookupTable.filters(ii,:)=single(LookupTable.SS.(LookupTable.fluortags{ii}).Filter);
                        LookupTable.wavelengths(ii,:)=single(LookupTable.SS.(LookupTable.fluortags{ii}).Wavelength);
                    end
                end
            end
            
            LookupTable.SpecMax=single(zeros(1,numel(LookupTable.fluortags)));
            for ii=1:numel(LookupTable.SpecMax)
                
                LookupTable.wavelengths(ii,(max(LookupTable.spectra(ii,:).*...
                    LookupTable.filters(ii,:))==(LookupTable.spectra(ii,:).*...
                    LookupTable.filters(ii,:))))
                
                LookupTable.SpecMax(ii)=...
                    LookupTable.wavelengths(ii,(max(LookupTable.spectra(ii,:).*...
                    LookupTable.filters(ii,:))==(LookupTable.spectra(ii,:).*...
                    LookupTable.filters(ii,:))));
            end
            LookupTable.nSpectrumPoints=17;
            LookupTable.deltalambda=0.002;
            
            [LookupTable.yy0,...
                LookupTable.xx0,...
                LookupTable.zzp,...
                LookupTable.lll]=ndgrid(LookupTable.y0lnspace,...
                LookupTable.x0lnspace,LookupTable.zplnspace,...
                LookupTable.SpecMax);
             
            LookupTable.codex=single(zeros(4,numel(LookupTable.xx0)));
            LookupTable.codex(1,:)=single(reshape(LookupTable.xx0,1,numel(LookupTable.xx0)));
            LookupTable.codex(2,:)=single(reshape(LookupTable.yy0,1,numel(LookupTable.yy0)));
            LookupTable.codex(3,:)=single(reshape(LookupTable.zzp,1,numel(LookupTable.zzp)));
            LookupTable.codex(4,:)=single(reshape(LookupTable.lll,1,numel(LookupTable.lll)));
            
            LookupTable.LT=single(zeros(GLMPP.K,GLMPP.K,size(LookupTable.codex,2)));
            
            LookupTable.LookupTableStructure=struct('codex',LookupTable.codex,...
                'LookupTable',LookupTable.LT);
            
            out = LookupTable;
        end
        function out = updategrid(LookupTable, deltax0in, deltay0in,...
                deltazpin, x0rangein, y0rangein, zprangein)
            LookupTable.deltax0=single(deltax0in); %in microns
            LookupTable.deltay0=single(deltay0in); %in microns
            LookupTable.deltazp=single(deltazpin); %in microns
            LookupTable.x0range=single(x0rangein);
            LookupTable.y0range=single(y0rangein);
            LookupTable.zprange=single(zprangein);
            LookupTable.numx0pts=single(round(...
                (LookupTable.x0range(2)-...
                LookupTable.x0range(1))/LookupTable.deltax0...
                ));
            LookupTable.numy0pts=single(round(...
                (LookupTable.y0range(2)-...
                LookupTable.y0range(1))/LookupTable.deltay0...
                ));
            LookupTable.numzppts=single(round(...
                (LookupTable.zprange(2)-...
                LookupTable.zprange(1))/LookupTable.deltazp...
                ));
            
            LookupTable.x0lnspace=single(linspace(...
                -LookupTable.deltax0*(LookupTable.numx0pts-1)/2,...
                 LookupTable.deltax0*(LookupTable.numx0pts-1)/2,...
                 LookupTable.numx0pts));
            LookupTable.y0lnspace=single(linspace(...
                -LookupTable.deltay0*(LookupTable.numy0pts-1)/2,...
                 LookupTable.deltay0*(LookupTable.numy0pts-1)/2,...
                 LookupTable.numy0pts));
            LookupTable.zplnspace=single(linspace(...
                -LookupTable.deltazp*(LookupTable.numzppts-1)/2,...
                 LookupTable.deltazp*(LookupTable.numzppts-1)/2,...
                 LookupTable.numzppts));
            [LookupTable.yy0,...
                LookupTable.xx0,...
                LookupTable.zzp,...
                LookupTable.lll]=ndgrid(LookupTable.y0lnspace,...
                LookupTable.x0lnspace,LookupTable.zplnspace,...
                LookupTable.SpecMax); 
            LookupTable.codex=single(zeros(4,numel(LookupTable.xx0)));
            LookupTable.codex(1,:)=single(reshape(LookupTable.xx0,1,numel(LookupTable.xx0)));
            LookupTable.codex(2,:)=single(reshape(LookupTable.yy0,1,numel(LookupTable.yy0)));
            LookupTable.codex(3,:)=single(reshape(LookupTable.zzp,1,numel(LookupTable.zzp)));
            LookupTable.codex(4,:)=single(reshape(LookupTable.lll,1,numel(LookupTable.lll)));
            
            LookupTable.LT=single(zeros(size(LookupTable.LT,1),size(LookupTable.LT,1),size(LookupTable.codex,2)));
            
            LookupTable.LookupTableStructure=struct('codex',LookupTable.codex,...
                'LookupTable',LookupTable.LT);
             
             
            out = LookupTable;
        end
        function out = create(LookupTable,GibsonLaniPSF)
            h=waitbar(0,'1','Name','calculating frames...',...
                'CreateCancelBtn','setappdata(gcbf,''canceling'',1)');
            for ii=1:size(LookupTable.LT,3)
                if getappdata(h,'canceling')
                    break
                end
                GibsonLaniPSF=GibsonLaniPSF.intens(...
                    LookupTable.codex(1,ii),...
                    LookupTable.codex(2,ii),...
                    LookupTable.codex(3,ii),...
                    LookupTable.codex(4,ii));
                
                %GibsonLaniPSF=GibsonLaniPSF.bead(...
                %    LookupTable.codex(1,ii),...
                %    LookupTable.codex(2,ii),...
                %    LookupTable.codex(3,ii),...
                %    LookupTable.codex(4,ii));
                
                LookupTable.LT(:,:,ii)=single(GibsonLaniPSF.PSF);
                
                LookupTable.LookupTableStructure.codex=LookupTable.codex;
                LookupTable.LookupTableStructure.LookupTable=LookupTable.LT;
                
                waitbar(ii/size(LookupTable.LT,3),h,sprintf(...
                '%d/%d frames',ii,...
                size(LookupTable.LT,3)));
            end
            delete(h)
            out = LookupTable;
        end
        function out = spectralcreate(LookupTable,GibsonLaniPSF)            
            h=waitbar(0,'1','Name','calculating frames...',...
                'CreateCancelBtn','setappdata(gcbf,''canceling'',1)');
            
            display(LookupTable.deltay0)
            LookupTable.deltazp
            LookupTable.x0range
            LookupTable.y0range
            LookupTable.zprange
            
            for ii=1:(size(LookupTable.LT,3)/numel(LookupTable.SpecMax))
                if getappdata(h,'canceling')
                    break
                end
                
                for jj=1:numel(LookupTable.SpecMax)
                    GibsonLaniPSF=GibsonLaniPSF.spectralintens(...
                        LookupTable.codex(1,ii),...
                        LookupTable.codex(2,ii),...
                        LookupTable.codex(3,ii),...
                        LookupTable.wavelengths(jj,:),...
                        LookupTable.spectra(jj,:),...
                        LookupTable.filters(jj,:));
                    LookupTable.LT(:,:,ii+(jj-1)*(size(LookupTable.LT,3)/numel(LookupTable.SpecMax)))=...
                        single(GibsonLaniPSF.spectralPSF);
                end
                
                LookupTable.LookupTableStructure.codex=LookupTable.codex;
                LookupTable.LookupTableStructure.LookupTable=LookupTable.LT;
                
                waitbar(ii/(size(LookupTable.LT,3)/numel(LookupTable.SpecMax)),h,sprintf(...
                '%d/%d frames',ii,...
                size(LookupTable.LT,3)/numel(LookupTable.SpecMax)));
            end
            delete(h)
            out = LookupTable; 
        end
        function out = spectralcreateCUSTOMPLATE(LookupTable,...
                GibsonLaniPSF, xoffsetin, yoffsetin, thetaoffsetin,...
                liveactuatorsin, actuatorheightsin)
                        
            h=waitbar(0,'1','Name','calculating frames...',...
                'CreateCancelBtn','setappdata(gcbf,''canceling'',1)');
            
            rhotemp=reshape(GibsonLaniPSF.rho(1,1,:),...
                [1,numel(GibsonLaniPSF.rho(1,1,:))]);
            thetatemp=reshape(GibsonLaniPSF.rho(1,1,:),...
                [1,numel(GibsonLaniPSF.rho(1,1,:))]);
            newTHETAplate=XPP(rhotemp,...
                thetatemp,...
                xoffsetin,...
                yoffsetin,...
                thetaoffsetin,...
                liveactuatorsin,...
                actuatorheightsin);
            
            for ii=1:numel(rhotemp)
                GibsonLaniPSF.THETAplate(:,:,ii)=newTHETAplate(ii);
            end
            
            for ii=1:(size(LookupTable.LT,3)/numel(LookupTable.SpecMax))
                if getappdata(h,'canceling')
                    break
                end
                
                for jj=1:numel(LookupTable.SpecMax)
                    GibsonLaniPSF=GibsonLaniPSF.spectralintens(...
                        LookupTable.codex(1,ii),...
                        LookupTable.codex(2,ii),...
                        LookupTable.codex(3,ii),...
                        LookupTable.wavelengths(jj,:),...
                        LookupTable.spectra(jj,:),...
                        LookupTable.filters(jj,:));
                    LookupTable.LT(:,:,ii+(jj-1)*(size(LookupTable.LT,3)/numel(LookupTable.SpecMax)))=...
                        single(GibsonLaniPSF.spectralPSF);
                end
                
                LookupTable.LookupTableStructure.codex=LookupTable.codex;
                LookupTable.LookupTableStructure.LookupTable=LookupTable.LT;
                
                waitbar(ii/(size(LookupTable.LT,3)/numel(LookupTable.SpecMax)),h,sprintf(...
                '%d/%d frames',ii,...
                size(LookupTable.LT,3)/numel(LookupTable.SpecMax)));
            end
            delete(h)
            out = LookupTable; 
        end
        function out = spectralstandardcreate(LookupTable,GibsonLaniPSF)            
            h=waitbar(0,'1','Name','calculating frames...',...
                'CreateCancelBtn','setappdata(gcbf,''canceling'',1)');
            
            display(LookupTable.deltay0)
            LookupTable.deltazp
            LookupTable.x0range
            LookupTable.y0range
            LookupTable.zprange
            
            for ii=1:(size(LookupTable.LT,3)/numel(LookupTable.SpecMax))
                if getappdata(h,'canceling')
                    break
                end
                
                for jj=1:numel(LookupTable.SpecMax)
                    GibsonLaniPSF=GibsonLaniPSF.spectralintensstandard(...
                        LookupTable.codex(1,ii),...
                        LookupTable.codex(2,ii),...
                        LookupTable.codex(3,ii),...
                        LookupTable.wavelengths(jj,:),...
                        LookupTable.spectra(jj,:),...
                        LookupTable.filters(jj,:));
                    LookupTable.LT(:,:,ii+(jj-1)*(size(LookupTable.LT,3)/numel(LookupTable.SpecMax)))=...
                        single(GibsonLaniPSF.spectralPSF);
                end
                
                LookupTable.LookupTableStructure.codex=LookupTable.codex;
                LookupTable.LookupTableStructure.LookupTable=LookupTable.LT;
                
                waitbar(ii/(size(LookupTable.LT,3)/numel(LookupTable.SpecMax)),h,sprintf(...
                '%d/%d frames',ii,...
                size(LookupTable.LT,3)/numel(LookupTable.SpecMax)));
            end
            delete(h)
            out = LookupTable; 
        end
        function out = filtersetstandardcreate(LookupTable,GLMPP,...
            GibsonLaniPSF,filterwidthvecin, mincutoffin, maxcutoffin)
            
            %redefine LT property to accomodate new size of lookuptable
            %entry the filter set scheme.
            LookupTable.LT=single(zeros(GLMPP.K,...
                GLMPP.K*numel(filterwidthvecin),...
                size(LookupTable.codex,2)));
            
            h=waitbar(0,'1','Name','calculating frames...',...
                'CreateCancelBtn','setappdata(gcbf,''canceling'',1)');
            
            for ii=1:(size(LookupTable.LT,3)/numel(LookupTable.SpecMax))
                if getappdata(h,'canceling')
                    break
                end
                
                GibsonLaniPSF=GibsonLaniPSF.fitlersetstandard(...
                    filterwidthvecin, mincutoffin, maxcutoffin,...
                    LookupTable.codex(1,ii),...
                    LookupTable.codex(2,ii),...
                    LookupTable.codex(3,ii),...
                    LookupTable.SS);
                
                for jj=1:numel(LookupTable.SpecMax)
                    LookupTable.LT(:,:,ii+(jj-1)*(size(LookupTable.LT,3)/numel(LookupTable.SpecMax)))=...
                        single(GibsonLaniPSF.filtersetpsfarray(:,:,jj));
                end
                
                LookupTable.LookupTableStructure.codex=LookupTable.codex;
                LookupTable.LookupTableStructure.LookupTable=LookupTable.LT;
                
                waitbar(ii/(size(LookupTable.LT,3)/numel(LookupTable.SpecMax)),h,sprintf(...
                '%d/%d frames',ii,...
                size(LookupTable.LT,3)/numel(LookupTable.SpecMax)));
            end
            delete(h)
            out = LookupTable; 
        end
        function out = createvarblur(LookupTable,GibsonLaniPSF)
            h=waitbar(0,'1','Name','calculating frames...',...
                'CreateCancelBtn','setappdata(gcbf,''canceling'',1)');
            for ii=1:size(LookupTable.LT,3)
                if getappdata(h,'canceling')
                    break
                end
                %GibsonLaniPSF=GibsonLaniPSF.intens(...
                %    LookupTable.codex(1,ii),...
                %    LookupTable.codex(2,ii),...
                %    LookupTable.codex(3,ii),...
                %    LookupTable.codex(4,ii));
                
                GibsonLaniPSF=GibsonLaniPSF.varblur(...
                    LookupTable.codex(1,ii),...
                    LookupTable.codex(2,ii),...
                    LookupTable.codex(3,ii),...
                    LookupTable.codex(4,ii));
                
                LookupTable.LT(:,:,ii)=single(GibsonLaniPSF.PSF);
                
                LookupTable.LookupTableStructure.codex=LookupTable.codex;
                LookupTable.LookupTableStructure.LookupTable=LookupTable.LT;
                
                waitbar(ii/size(LookupTable.LT,3),h,sprintf(...
                '%d/%d frames',ii,...
                size(LookupTable.LT,3)));
            end
            delete(h)
            out = LookupTable; 
        end
        function out = write(LookupTable,LookupTableFileName)
            fnm=LookupTableFileName;
            LTS=LookupTable.LookupTableStructure;
            save(fnm,'-struct','LTS');
            
            out = fnm;
        end
    end
end
